import { describe, expect, it } from "vitest";
import cases from "../../flag-core/conformance/cases.json";
import { evaluate } from "./index";
import type { FlagRule } from "./index";

interface ConformanceCase {
  flag: FlagRule;
  unitId: string;
  expected: { enabled: boolean; variant: string | null; reason: string };
}

// The fixture is generated by the Python engine; this proves the TS engine
// produces identical decisions for every case (the Rust crate asserts it on CI).
describe("conformance fixture", () => {
  it("the TS engine matches every case", () => {
    const all = cases as unknown as ConformanceCase[];
    expect(all.length).toBeGreaterThan(0);
    for (const c of all) {
      const d = evaluate(c.flag, { unitId: c.unitId });
      expect({ enabled: d.enabled, variant: d.variant, reason: d.reason }).toEqual(c.expected);
    }
  });
});
